"""
Trip report generator.

Reads logs/events.jsonl (written by main.py) and produces a markdown summary.
Hybrid: uses the local LLM (SmolLM2) if available, falls back to a pure
template otherwise.

Usage:
  python scripts/report.py                       # default log path
  python scripts/report.py --events logs/events.jsonl --out output/benchmarks/trip_report.md
  python scripts/report.py --use-llm            # force LLM even if config says off
"""
import argparse
import json
import os
import sys
from collections import Counter
from typing import List, Optional

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from src.config import LOG_DIR, LLM_MODEL_PATH, LLM_ENABLED, LLM_N_CTX, LLM_N_THREADS


def load_events(path: str) -> List[dict]:
    if not os.path.exists(path):
        return []
    out = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return out


def template_summary(events: List[dict]) -> str:
    if not events:
        return "_No events recorded._"

    counts = Counter(e["event_type"] for e in events)
    first_ts = min(e["timestamp"] for e in events)
    last_ts = max(e["timestamp"] for e in events)
    duration_min = (last_ts - first_ts) / 60.0

    rows = []
    for et, n in counts.most_common():
        rows.append(f"| {et} | {n} |")
    table = "| Event | Count |\n|---|---:|\n" + "\n".join(rows)

    notable = [e for e in events
               if e["event_type"] in ("DROWSINESS", "PHONE_USAGE", "NO_FACE", "DISTRACTION")]
    note_block = ""
    if notable:
        bullets = []
        for e in notable[:5]:
            t = e.get("timestamp", 0)
            mm = int((t - first_ts) // 60)
            ss = int((t - first_ts) % 60)
            bullets.append(f"- **{mm:02d}:{ss:02d}** — {e['event_type']}: {e.get('message','')}")
        note_block = "\n\nNotable moments:\n" + "\n".join(bullets)

    return f"""# Trip Report

- **Duration:** {duration_min:.1f} min
- **Total events:** {len(events)}

{table}
{note_block}

_Generated by template (LLM not available)._
"""


def llm_summary(events: List[dict]) -> Optional[str]:
    if not os.path.exists(LLM_MODEL_PATH):
        return None
    try:
        from llama_cpp import Llama
    except ImportError:
        return None

    counts = Counter(e["event_type"] for e in events)
    sample = events[-15:] if len(events) > 15 else events
    payload = {
        "total_events": len(events),
        "counts": dict(counts),
        "recent_sample": [{"t": e["timestamp"], "type": e["event_type"],
                            "message": e.get("message","")} for e in sample],
    }

    try:
        llm = Llama(model_path=LLM_MODEL_PATH, n_ctx=LLM_N_CTX,
                    n_threads=LLM_N_THREADS, verbose=False)
    except Exception as e:
        print(f"[report] LLM load failed: {e}")
        return None

    prompt = (
        "<|im_start|>system\n"
        "You are a fleet safety analyst. Write a concise trip report (3 short paragraphs max) "
        "based on the JSON. Use plain markdown. Highlight any safety concerns. "
        "No filler, no apology, no introduction.<|im_end|>\n"
        f"<|im_start|>user\n{json.dumps(payload, indent=2)}<|im_end|>\n"
        "<|im_start|>assistant\n"
    )
    try:
        r = llm(prompt, max_tokens=300, temperature=0.3, stop=["<|im_end|>"])
        text = r["choices"][0]["text"].strip()
        return f"# Trip Report (LLM-generated)\n\n{text}\n"
    except Exception as e:
        print(f"[report] LLM infer failed: {e}")
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", default=os.path.join(LOG_DIR, "events.jsonl"))
    ap.add_argument("--out", default=os.path.join(ROOT, "output", "benchmarks", "trip_report.md"))
    ap.add_argument("--use-llm", action="store_true", help="Force LLM attempt even if disabled in config")
    args = ap.parse_args()

    events = load_events(args.events)
    print(f"Loaded {len(events)} events from {args.events}")

    md = None
    if LLM_ENABLED or args.use_llm:
        md = llm_summary(events)
        if md:
            print("Generated via LLM.")
    if md is None:
        md = template_summary(events)
        print("Generated via template.")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(md)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
